### ISSUE TITLE
How to use the code for training on Tusimple Dataset

### ISSUE THREAD

**Issue by wxiangxiaow** [ibrahimgh25/EL-GAN-Implementation#1]
Thanks for your great work!
Could you please write a more detailed README for using Tusimple Dataset? Like how the dataset and code files should be arrange? If you had done this work, please tell me how to find.
Thank you again!

**Comment by ibrahimgh25** [comment]
Regarding using the Tusimple, the [training_utils.dataset](https://github.com/ibrahimgh25/EL-GAN-Implementation/blob/main/training_utils/dataset.py ) class defines how the dataset is loaded into pytorch.
When I used the code, I downloaded the dataset from [here](https://github.com/TuSimple/tusimple-benchmark/issues/3) (I believe i used images from test_set.zip). After you download the dataset, unzip it in some directory, which you'll pass to the dataset constructor. (see how the dataloaders are defined in elgan_training.py[](https://github.com/ibrahimgh25/EL-GAN-Implementation/blob/main/elgan_training.py).
Regarding updating the README, please confirm that the steps I shared with you work and then I could add them to the README.
